### PR TITLE
Allows sending of link code to AmongUsCapture

### PR DESCRIPTION
**Pull request by corylulu**
https://github.com/denverquane/amonguscapture/pull/35

### CODE REVIEW

**Comment by Stenlan** [comment]
Why would you need to send a linking code if you're already linked? Unless I'm misunderstanding, you can't send the linking code before you're, well, linked.

**Comment by corylulu** [comment]
Maybe I have something wrong in my setup, but my AmongUsCapture will be connected to the websocket, but if I type `.au new <code> <region>` in discord, it will 100% prompt me to enter a code to link it to the capture. I've looked at the code fairly loosely, but I haven't figured out what directly links up the capture to the AmongUsDiscord without manually entering a link code.

**Comment by Stenlan** [comment]
You indeed have to enter the code into the capture. This is because we want to be able to support multiple instances of the capture software on the same discord bot, so there has to be a way for the user to specify what guild they want to link their capture software to. If you want just a 1:1 connection like you're doing now, you can do away with the concept of linking codes entirely. But in our case, we can't do that, and we can't use your approach either, because we wouldn't know what instance to send the linking code to -- that's what the linking code is used for; to differentiate between different socket instances.

**Comment by corylulu** [comment]
I could change it so it would only work for localhost connection or create a new `SINGLE_INSTANCE_MODE` or `AUTO_LINK_LOCAL_CAPTURE` environment variable for auto connecting.

**Comment by denverquane** [comment]
We're attempting to build a solution that avoids the need for capture/connect codes entirely, but simultaneously needs to be flexible to *any guild being mapped to any capture client* (for the use case of this bot being deployed in tons of servers simultaneously). If you wanted to make another PR for a single instance mode, or in general making it very explicit that it would work for only 1 guild -despite this being somewhat antithetical to this bot's purpose- then I can review that PR instead :)

**Pull request closed without merging**
